Basic and messy process_wait() seems to work
Processes keep track of their children in the `thread` struct. Each
thread acquires a lock when it starts and releases the lock when it
dies. process_wait() finds the child that it is waiting for and tries to
acquire this "life lock".

Current implementation is very messy.

Output of `pintos --filesys-size=2 -p ../../examples/echo -a echo -- -f -q run 'echo one two three'`:

Copying ../../examples/echo to scratch partition...
squish-pty bochs -q
========================================================================
                       Bochs x86 Emulator 2.6.8
                Built from SVN snapshot on May 3, 2015
                  Compiled on Dec 21 2015 at 22:53:23
========================================================================
00000000000i[      ] BXSHARE not set. using compile time default '/usr/local/bochs-osc/share/bochs'
00000000000i[      ] reading configuration from bochsrc.txt
00000000000e[      ] bochsrc.txt:8: 'user_shortcut' will be replaced by new 'keyboard' option.
00000000000i[      ] installing nogui module as the Bochs GUI
00000000000i[      ] using log file bochsout.txt
PiLo hda1
Loading...........
Kernel command line: -f -q extract run 'echo one two three'
Pintos booting with 4,096 kB RAM...
383 pages available in kernel pool.
383 pages available in user pool.
Performed fack attempt to acquire lock
Calibrating timer...  204,600 loops/s.
hda: 5,040 sectors (2 MB), model "BXHD00011", serial "Generic 1234"
hda1: 176 sectors (88 kB), Pintos OS kernel (20)
hda2: 4,096 sectors (2 MB), Pintos file system (21)
hda3: 80 sectors (40 kB), Pintos scratch (22)
filesys: using hda2
scratch: using hda3
Formatting file system...done.
Boot complete.
Extracting ustar archive from scratch device into file system...
Putting 'echo' into the file system...
Erasing ustar archive...
Executing 'echo one two three':
Performed fack attempt to acquire lock
echo one two three
system call: exit
Execution of 'echo one two three' complete.
Timer: 278 ticks
Thread: 61 idle ticks, 192 kernel ticks, 27 user ticks
hda2 (filesys): 53 reads, 164 writes
hda3 (scratch): 79 reads, 2 writes
Console: 971 characters output
Keyboard: 0 keys pressed
Exception: 0 page faults
Powering off..========================================================================
Bochs is exiting with the following message:
[UNMAP ] Shutdown port: shutdown requested
========================================================================